### ISSUE TITLE
Chair of Finance Committee Redundant

### ISSUE THREAD

**Issue by sbalassy** [CMU-Senate/bylaws#16]
There is a section that has duties/powers of the Chair of the Finance Committee. There is also a section for duties/powers of Committees. For some reason, in this area there lists a second instance of Finance Chair duties/powers (and not for others). This may be redundant and should be straightened out.

**Comment by nikkiam** [comment]
As far as I can tell, the reason the chair of the finance committee has this section is because of their elevated position (i.e. the ability to audit student organisations). Its structure is in line with the officer positions as laid out in the constitution itself, therefore it seems as if it should just stay as is for the time being.
